blog/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', PostView.as_view()),
    path('<int:art_id>/', PostSingle.as_view()),
    path('filter/', get_art_filter),
    path('comments/<int:art_id>/', AddComments.as_view(), name='add_comments'),
    path('<int:art_id>/like/', AddLike.as_view(), name='add_like'),
    path('<int:art_id>/del_like/', DelLike.as_view(), name='del_like'),
    path('search/', SearchView.as_view(), name='search_results'),
]

my_blog/urls.py
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.conf.urls import include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


# Create your models here.
class Post(models.Model):
    """ Данные о статье """
    TOPIC_TYPES = [
        (1, 'Цветы комнатные'),
        (2, 'Цветы однолетние'),
        (3, 'Цветы многолетние'),
        (4, 'Декоративные кустарники'),
    ]
    title = models.CharField('Название статьи', max_length=150)
    text = models.TextField('Текст статьи')
    author = models.CharField('Автор', max_length=100)
    data = models.DateField('Дата публикации')
    img = models.ImageField('Изображение', upload_to='image/%Y')
    type = models.IntegerField(choices=TOPIC_TYPES)

    def __str__(self):
        return f'{self.title}, {self.author}'

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи сайта'


class Comments(models.Model):
    """Комментарии"""

    email = models.EmailField()
    name = models.CharField('Имя', max_length=50)
    text_comment = models.TextField('Текст комментария', max_length=1500)
    post = models.ForeignKey(Post, verbose_name='Статья', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}, {self.post}, {self.text_comment}'

    class Meta:
        ordering = ['-id']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Likes(models.Model):
    """ Лайки для статьи """

    ip = models.CharField('IP-адрес', max_length=100)
    post_id = models.ForeignKey(Post, verbose_name='Статья', on_delete=models.CASCADE)

blog/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from .models import Post, Likes
from .form import CommentsForm
from django.core.paginator import Paginator
from django.db.models import Q
from django.views.generic import ListView
from .form import SearchForm



# Create your views here.
class PostView(View):
    """ Вывод статей """

    def get(self, request):
        posts = Post.objects.order_by('-id')
        paginator = Paginator(posts, 3)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request, 'blog/articals.html', {'page_obj': page_obj})


def get_art_filter(request):
    topic_type = request.GET.get('type', None)
    if topic_type:
        queryset = Post.objects.filter(type=topic_type).order_by('-id')
    else:
        queryset = Post.objects.order_by('-id')

    paginator = Paginator(queryset, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'blog/articals.html', context)


class PostSingle(View):
    """  Одна статья отдельно и подробно """

    def get(self, request, art_id):
        post = Post.objects.get(id=art_id)
        return render(request, 'blog/single.html', {'post': post})


class AddComments(View):
    """ Добавление комментариев """

    def post(self, request, art_id):
        form = CommentsForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.post_id = art_id
            form.save()
        return redirect(f'/{art_id}')


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


class AddLike(View):
    def get(self, request, art_id):
        ip_client = get_client_ip(request)
        try:
            Likes.objects.get(ip=ip_client, post_id=art_id)
            return redirect(f'/{art_id}')
        except:
            post = Post.objects.get(id=art_id)
            new_like = Likes()
            new_like.ip = ip_client
            new_like.post_id = post
            new_like.save()
            return redirect(f'/{art_id}')


class DelLike(View):
    def get(self, request, art_id):
        ip_client = get_client_ip(request)
        try:
            like = Likes.objects.get(ip=ip_client, post_id=art_id)
            like.delete()
            return redirect(f'/{art_id}')
        except:
            return redirect(f'/{art_id}')


class SearchView(ListView):
    model = Post
    template_name = 'blog/search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        print(query)
        if query:
            object_list = Post.objects.filter(
                Q(title__icontains=query) | Q(text__icontains=query)
            )
        else:
            object_list = Post.objects.none()
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q', '')
        context['form'] = SearchForm(self.request.GET)
        return context

templates/blog/articals.html
<!DOCTYPE>
{% load static %}
<html >
<head>
	<title>Мой блог</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />

	<link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" />

</head>
<body>
<div class="shell">
	<div class="border">

		<div id="navigation_adm">
			<ul>
			    <li><a href="/" class="active">Главная</a></li>
			    <li><a href="/admin">Админ панель</a></li>
			    
			</ul>
		</div>

<form action="{% url 'search_results' %}" method="get">
  {% csrf_token %}
  <input type="text" name="q" placeholder="Поиск..." value="{{ query }}">
  <button type="submit">Найти</button>
</form>



        <div id="navigation">
			<ul>
			    <li><a href="/filter/?type=1">Цветы комнатные</a></li>
			    <li><a href="/filter/?type=2">Цветы однолетние</a></li>
                <li><a href="/filter/?type=3">Цветы многолетние</a></li>
			    <li><a href="/filter/?type=4">Декоративные кустарники</a></li>

			</ul>
		</div>


		<div id="main">
			<div id="content" class="left">
				
				<div class="projects">
					<h3>Записи</h3>
                    {% for post in page_obj %}
					<div class="item">
						<div class="image left">
							<img src="{{ post.img.url }}" width="200px" alt="" />
						</div>
						<div class="text left">
                            <br>
							<h4><a href="/{{ post.id }}">{{ post.title }}</a></h4>
							<p>{{ post.text|safe|truncatechars:140 }}</p>
							<p>Автор: {{ post.author }}</p>
						</div>

						<div class="cl">&nbsp;</div>
					</div>

					{% endfor %}
				</div>

            <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; Первая страница</a>
            <a href="?page={{ page_obj.previous_page_number }}">Предыдущая страница</a>
        {% endif %}

        <span class="current">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Следующая страница</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Последняя страница &raquo;</a>
        {% endif %}
    </span>
</div>




			</div>
			
			<div class="cl">&nbsp;</div>
		</div>
		

	</div>
	
	<div id="footer">
		<p class="copy right">Copyright &copy;  2023 </p>
	</div>
</div>
</body>
</html>

templates/blog/search_results.html
<!DOCTYPE>
{% load static %}
<html >
<head>
	<title>{{ post.title }}</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />

	<link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" />

</head>
<body>
<div class="shell">
	<div class="border">

		<div id="navigation_adm">
			<ul>
			    <li><a href="/" class="active">Главная</a></li>
			    <li><a href="/admin">Админ панель</a></li>

			</ul>
		</div>


        <div id="navigation">
			<ul>
			    <li><a href="/filter/?type=1">Цветы комнатные</a></li>
			    <li><a href="/filter/?type=2">Цветы однолетние</a></li>
                <li><a href="/filter/?type=3">Цветы многолетние</a></li>
			    <li><a href="/filter/?type=4">Декоративные кустарники</a></li>

			</ul>
		</div>

    <h1>Результаты поиска</h1>

    <form action="{% url 'search_results' %}" method="get">
      {% csrf_token %}
      <input type="text" name="q" placeholder="Поиск..." value="{{ query }}">
      <button type="submit">Найти</button>
    </form>

    {% if object_list %}
        <div class="list">
        <ul>
        {% for post in object_list %}

                <li>
                   <H2> <a href="/{{ post.id }}">{{ post.title }}</a></H2>
                    <p>{{ post.text|slice:":200"|safe }}...</p>
                </li>

        {% endfor %}
        </ul>
        </div>
    {% else %}
        <p>Ничего не найдено</p>
    {% endif %}

	<div id="footer">
		<p class="copy right">Copyright &copy;  2023 </p>
	</div>
</div>
</body>
</html>

templates/blog/single.html
<!DOCTYPE>
{% load static %}
<html >
<head>
	<title>{{ post.title }}</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />

	<link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" />

</head>
<body>
<div class="shell">
	<div class="border">

		<div id="navigation_adm">
			<ul>
			    <li><a href="/" class="active">Главная</a></li>
			    <li><a href="/admin">Админ панель</a></li>

			</ul>
		</div>

<form action="{% url 'search_results' %}" method="get">
  {% csrf_token %}
  <input type="text" name="q" placeholder="Поиск..." value="{{ query }}">
  <button type="submit">Найти</button>
</form>


        <div id="navigation">
			<ul>
			    <li><a href="/filter/?type=1">Цветы комнатные</a></li>
			    <li><a href="/filter/?type=2">Цветы однолетние</a></li>
                <li><a href="/filter/?type=3">Цветы многолетние</a></li>
			    <li><a href="/filter/?type=4">Декоративные кустарники</a></li>

			</ul>
		</div>


		<div id="main">
			<div id="content" class="left">

				<div class="projects">
					<h1>{{ post.title }}</h1>
                    <p class="data">Дата публикации: {{ post.data }}</p>
                   <p>
                       <img src="{{ post.img.url }}" width="50%" alt="" />
                   </p>
					<div class="item">

						<div class="text left">

							<article>{{ post.text|safe }}</article>
							<p>Автор: {{ post.author }}</p>
						</div>
						<div class="cl">&nbsp;</div>
					</div>

				</div>
			</div>

			<div class="cl">&nbsp;</div>
		</div>

        <div class="like">
            <br>
            <p>Понравилось: {{ post.likes_set.all.count }}</p>
            <br>
            <a href="{% url 'add_like' post.id %}">Нравится</a>&nbsp; &nbsp;
            <a href="{% url 'del_like' post.id %}">Не нравится</a>
        </div>


        <div class="form_comments">
            <h3>Оставить комментарий:</h3>
            <div>
                <form action="{% url 'add_comments' post.id %}" method="post">
                    {% csrf_token %}
                    <div>
                        <label>Ваш комментарий:</label>
                        <textarea name="text_comment"></textarea>
                    </div>
                    <div>
                        <label>Ваше имя * :</label>
                        <input name="name" type="text">
                    </div>
                    <div>
                        <label>Ваш email * :</label>
                        <input name="email" type="email">
                    </div>
                    <div>
                        <input type="submit">
                    </div>


                </form>
            </div>
        </div>

        <div class="comments">
            {% for comment in post.comments_set.all %}
                <h4>{{ comment.name }} : </h4>
                <p>
                    "{{ comment.text_comment }}"
                </p>
                <br>
            {% endfor %}
        </div>


	</div>

	<div id="footer">
		<p class="copy right">Copyright &copy;  2023 </p>
	</div>
</div>
</body>
</html>